version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: pokemon
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./script/creation_tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6033:3306"