logging:
  level:
    root: DEBUG
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  service:
    aaa:
      paths:
        app-public-path: /pokes/**
  email: redouane@esei.uvigo.es
  thread-pool: 10